### ISSUE TITLE
docType must be also required

### ISSUE THREAD

**Issue by alfredomp** [SPINEProject/SPINE-json-schema#42]
https://github.com/SPINEProject/SPINE-json-schema/blob/a3b289c5e0955edeabbd0ef7d179f13534daa092/schemas/cohort.schema.json#L141

@katiamar63  could you add the docType to the required properties?

**Comment by katiamar63** [comment]
OK, so far it was not required by convention but it is a good idea

**Comment by katiamar63** [comment]
Change applied in commit above
